### ISSUE TITLE
PDF Badge "broken"

### ISSUE THREAD

**Issue by laam4** [panunu/metropolia-thesis-latex#10]
PDF badge is broken at the moment. @panunu has to enable it at sharelatex https://www.sharelatex.com/github/

The old button was referring to my fork repo and I can't enable it for this one, only creator of the repo can do it.

**Comment by laam4** [comment]
pls

**Comment by panunu** [comment]
Ah, sry, will check this at some point again.

Not sure if I can enable it because the app requires quite a lot of account-wide permissions (including organisations aka clients'  repositories which I belong to). Are you aware of any not so permission-hungry alternatives?

**Comment by laam4** [comment]
hmmmm,

"Third-party application restrictions allow organization admins to restrict an untrusted application's access to the organization's data. Organization members are then free to use third-party applications for their personal user accounts while keeping organization data safe."

Also: "When an organization has not set up third-party application restrictions, any third-party application authorized by an organization member can also access the organization's private resources." Both from https://help.github.com/articles/about-third-party-application-restrictions/

**Comment by patrick-ausderau** [comment]
We should try to convince metropolia to install their own sharelatex server ;)

**Comment by laam4** [comment]
These are the permissions which sharelatex app needs:
* Full control of repository hooks
* Read org and team membership
* Access commit status
* Access user emails (readonly)

**Comment by panunu** [comment]
The trouble is that I do not necessarily have administrator-level permissions on all organisations.

But does Metropolia have an official GitHub account? We could transfer this repo there. Ping @linjaaho ? :-)

**Comment by patrick-ausderau** [comment]
I added instructions in readme on how to manually use the template with shareLaTeX. 
Should we remove the badge?

**Comment by panunu** [comment]
I removed the badge for now. 

Hopefully we could transfer this repository to a Metropolia organisation.

**Comment by laam4** [comment]
Sharelatex already removed the whole github feature, because it wasn't used very much :D https://www.sharelatex.com/learn/Kb%2FWhere%20is%20Github%20CI
