### ISSUE TITLE
Switch to biber biblatex

### ISSUE THREAD

**Issue by patrick-ausderau** [panunu/metropolia-thesis-latex#14]
Among few advantages compare to old bibtex8: \citeauthor and \citeyear (e.g. for copied figure caption), having the \cites for multi-cites with page numbers,...

Only problem, there is no default Vancouver style: 
https://tex.stackexchange.com/questions/290360/how-to-use-vancouver-citation-style-with-biber-biblatex

**Comment by Mikaa** [comment]
Tällä saa lähteet `biblatex`:in kanssa näkymään:

`\usepackage[backend=biber,bibencoding=utf8,citetracker=true,isbn=true,doi=true,url=true,usetranslator=true,style=numeric-comp,citestyle=numeric,terseinits=false,giveninits=true,sorting=none]{biblatex}

% set right format
%\DeclareNameAlias{sortname}{last-first} % deprecated
\DeclareNameAlias{author}{family-given}
\DeclareFieldFormat{labelnumberwidth}{#1} % remove () from label number
\DeclareFieldFormat{title}{"#1"} % quotes to the title
\DeclareFieldFormat{journaltitle}{#1} % remove underline
\DeclareFieldFormat*{url}{\textless\url{#1}\textgreater} % you can modify how to url looks here
\DeclareFieldFormat{urlseen}{#1} 
%try set translation to biblio
\DefineBibliographyStrings{english}{%
  urlfrom = {available at},%
  urlseen = {visited on},%
  fromenglish = {from English},%
  fromfinnish = {from Finnish},%
  fromgerman = {from German},%
  fromjapanese = {from Japanese},%
  
}
\DefineBibliographyStrings{finnish}{%
%  urlfrom={Linkki: },%
  urlfrom={},%
  urlseen={Katsottu },%
  fromjapanese = {japanista},%
  fromenglish = {englannista},%
  fromfinnish = {suomesta},%
  fromgerman = {saksasta},%
}
{
%new cite command: "Vancouver Short"
\DeclareCiteCommand{\citeVS}
  {\usebibmacro{prenote}}
  {\usebibmacro{author}, \usebibmacro{title}}
  {\multicitedelim}
  {\usebibmacro{postnote}}

% new cite command: "Vancouver Short Collection" - necessary when referencing whole collections. 
\DeclareCiteCommand{\citeVSc}
  {\usebibmacro{prenote}}
  {\usebibmacro{editor}, \usebibmacro{title}}
  {\multicitedelim}
  {\usebibmacro{postnote}}
}

\addbibresource{biblio.bib}% for biblatex you need out \printbibliography too
%forcing single line spacing in bibliography
\DisemulatePackage{setspace}
`

**Comment by Mikaa** [comment]
Tällä saa lähteet `biblatex`:in kanssa näkymään:

`\usepackage[backend=biber,bibencoding=utf8,citetracker=true,isbn=true,doi=true,url=true,usetranslator=true,style=numeric-comp,citestyle=numeric,terseinits=false,giveninits=true,sorting=none]{biblatex}

% set right format
%\DeclareNameAlias{sortname}{last-first} % deprecated
\DeclareNameAlias{author}{family-given}
\DeclareFieldFormat{labelnumberwidth}{#1} % remove () from label number
\DeclareFieldFormat{title}{"#1"} % quotes to the title
\DeclareFieldFormat{journaltitle}{#1} % remove underline
\DeclareFieldFormat*{url}{\textless\url{#1}\textgreater} % you can modify how to url looks here
\DeclareFieldFormat{urlseen}{#1} 
%try set translation to biblio
\DefineBibliographyStrings{english}{%
  urlfrom = {available at},%
  urlseen = {visited on},%
  fromenglish = {from English},%
  fromfinnish = {from Finnish},%
  fromgerman = {from German},%
  fromjapanese = {from Japanese},%
  
}
\DefineBibliographyStrings{finnish}{%
%  urlfrom={Linkki: },%
  urlfrom={},%
  urlseen={Katsottu },%
  fromjapanese = {japanista},%
  fromenglish = {englannista},%
  fromfinnish = {suomesta},%
  fromgerman = {saksasta},%
}
{
%new cite command: "Vancouver Short"
\DeclareCiteCommand{\citeVS}
  {\usebibmacro{prenote}}
  {\usebibmacro{author}, \usebibmacro{title}}
  {\multicitedelim}
  {\usebibmacro{postnote}}

% new cite command: "Vancouver Short Collection" - necessary when referencing whole collections. 
\DeclareCiteCommand{\citeVSc}
  {\usebibmacro{prenote}}
  {\usebibmacro{editor}, \usebibmacro{title}}
  {\multicitedelim}
  {\usebibmacro{postnote}}
}

\addbibresource{biblio.bib}% for biblatex you need out \printbibliography too
%forcing single line spacing in bibliography
\DisemulatePackage{setspace}
`

**Comment by patrick-ausderau** [comment]
@Mikaa, thanks! Is the attribution (in Readme.md and main.tex) ok for you?
