### ISSUE TITLE
Switch from listings to minted for source code

### ISSUE THREAD

**Issue by patrick-ausderau** [panunu/metropolia-thesis-latex#15]
Some pros: better syntax highlighting and more languages supported.
Some cons: require external python pigment app and -shell-escape flag for compiling.

**Comment by panunu** [comment]
More pros: this seems to be supported in Sharelatex https://www.sharelatex.com/learn/Code_Highlighting_with_minted

**Comment by Mikaa** [comment]
"minted has the disadvantage that it needs a tool outside of texlive (pygmentize), listings and verbatim are pure LaTeX".
